version: '3.4'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: egzaminas
      MYSQL_DATABASE: egzaminas
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
    volumes:
     - ./database.sql:/docker-entrypoint-initdb.d/database.sql
     - ./my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80
    restart: always